### ISSUE TITLE
Net display layout

### ISSUE THREAD

**Issue by AgainPsychoX** [ADIOP55550/PNES-v3#15]
Nets need to be easy to be made easy to read without user moving each node pixel perfect...

### TODO

- [ ] "Net layout" menu _(or submenu in "View" or "Organize"/"Edit" menu)_
- [ ] Automatic layout strategies
- [ ] Grids
- [ ] Direction
- [ ] Distances
- [ ] Minimalizing edges, bends
- [ ] Grouping elements by type (places and transitions)
- [ ] Allow partial layout applying (only to selection)
- [ ] Push layout employment to history stack to allow Ctrl+Z (grouped, not as individual node moves)
- [ ] Grouping elements by tags (or common styles? common names?)

### Layout strategies ideas

- [ ] TBA

### Useful resources

* https://www.baeldung.com/cs/graph-auto-layout-algorithm
* https://www.yworks.com/pages/interactive-showcase-of-graph-layouts
* https://www.mindfusion.eu/graph-layout.html
* https://live.yworks.com/demos/layout/layoutstyles/
