### ISSUE TITLE
Undo/Redo system

### ISSUE THREAD

**Issue by AgainPsychoX** [ADIOP55550/PNES-v3#16]
Any editor need this essential thing.

### TODO

- [x] System to store changes (hybrid generative and save state[^1])
- [x] Menu "Edit" with "Undo" and "Redo" (possibly with minimalistic description what about)
- [x] Keyboard shortcuts
- [x] Basic usage (moving nodes for now)
- [ ] Allow grouping undoable actions (will come handy for cumulative actions)

##### Known issues

_(checked = fixed)_

- [x] Keyboard shortcuts doesn't work all the time
- [ ] Limit undo history length (or group old actions into larger chunks using save state) to prevent higher memory usage in intensive session
- [x] Prevent undo while network is being simulated (running).

##### Extra features

- [x] Sound alert when no more actions to undo/redo.

### Classes

- [x] `UndoHistory`
- [x] `UndoableAction` (provides way to undo it)
- [ ] `HardlyUndoableAction` (can't provide way to undo it, state needs to be read from saved)
- [x] `MoveNodeAction`
- [ ] `UndoableGroup`

### Useful resources

[^1]: https://stackoverflow.com/questions/3541383/undo-redo-implementation
