### ISSUE TITLE
Rewrite default mouse manager in visualizer

### ISSUE THREAD

**Issue by AgainPsychoX** [ADIOP55550/PNES-v3#27]
The default mouse manager used in the GraphStream graph view is hard to base from and its missing few features we would love to use.

### TODO

- [x] Selecting single element (`ui.selected` attribute)
- [x] Selecting area of elements
- [x] Extending/ selection when holding shift (both single/area; RTS-like)
- [x] Moving single element
- [x] Moving selection of elements (would be impossible without the rewrite)
- [x] Clicking single element (`ui.clicked` attribute)
- [x] Hover detection (`ui.mouseOver` attribute)
- [ ] Prevent unselecting on right click
- [ ] Mark preselected elements (`ui.preselected` attribute)

#### Other

- [ ] Snaping to grids
- [ ] Rotate selected elements positions around the point (while holding `R`?)
- [ ] Spread selected elements positions on line (while holding `L`?)
- [ ] Scale selected elements positions away from the point (while holding `S`?)
- [ ] Gravity move selected elements positions towards the point (while holding `G`?)
- [ ] There might be way to implement a bit smoother scaling and moving around the graph (as the mouse manager runs on the thread used to display graph)
